// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import HomeHero from './HomeHero';
import Image from './Image';
import ImageCards from './ImageCards';
import PageHero from './PageHero';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';
import Video from './Video';

export {
	Hero,
	HomeHero,
	Image,
	ImageCards,
	PageHero,
	Quote,
	Text,
	TextWithImage,
	Video,
};

export const components = {
	hero: Hero,
	home_hero: HomeHero,
	image: Image,
	image_cards: ImageCards,
	page_hero: PageHero,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
	video: Video,
};
